---
version: '3'
services:
  postgres:
    image: postgres:14.2
    container_name: lego_searcher-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: postgres
